config/routes.rb
Rails.application.routes.draw do
  #get 'calories/new'
  #get 'calories/show'
  #get 'calories/index'
  #get 'calories/edit'
  #get 'calories/create'
  #get 'calories/destroy'
  #resources :calories
  devise_for :users
  resources :calories
  #get 'charts/index'
  get 'charts/calories_logs'
  #get 'charts/filterd_logs'
  #resources :charts
  #namespace :charts do
  #  get "calories_logs"
  #end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calory.rb
class Calory < ApplicationRecord
  belongs_to :user
  validates :calories_number, presence: true,
                              length: {maximum: 4},
                              numericality: { only_integer: true,
                                              greater_than_or_equal_to: 0,
                                              less_than_or_equal_to: 2500 }
  #validates :calories_type, presence: true
  validates :calories_related_activity, presence: true, length: { maximum: 140}
  paginates_per 10


  def self.search
    raise params.inspect
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :calory 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery



end

app/controllers/calories_controller.rb
class CaloriesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]


  def new
    @calory = Calory.new
    #@user = current_user
    #raise params.inspect
  end

  def create
    current_user
    @calory = Calory.new(calory_params)
    @calory.user = current_user
    if @calory.save
         flash[:success] = 'New Calories Log Created'
         redirect_to calories_path
    else
         flash.now[:danger] = 'Error while creating Calories Log'
         render "new"
    end
  end

  def show
    @calory = Calory.find(params[:id])
  end

  def index

      if params[:date] && params[:date]!= ""
        date = params[:date].to_date
        #raise params.inspect
        @calories = current_user.calory.where('created_at > ? and created_at < ?', date.midnight - 1.day, date.midnight + 1.day).page(params[:page])
      elsif
        @calories = current_user.calory.page(params[:page])
      end
  end

  def edit
    id = params[:id]
    @calory = Calory.find(id)

  end

  def update
    @calory = Calory.find(params[:id])
    #current_user
    if @calory.update(calory_params)
      redirect_to calories_path
      flash[:success] = 'Calory Log Updated'
    else
      render 'edit'
    end

  end

  def destroy
    @calory = Calory.find(params[:id])
    @calory.delete
    redirect_to root_path
    flash[:warning] = 'Calories Log Deleted'
  end


  private

  def calory_params
    params.require(:calory).permit(:calories_number, :calories_type, :calories_related_activity, :user_id, :date)
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

=begin
  def filterd_logs
      @calories_burnt = current_user.calory.where("calories_type = ?", true)

  end
=end
=begin
  def calories_logs
    @calories_log = current_user.calory.group_by_week(:created_at).sum(:calories_number)
    #raise params.inspect
    render json: @calories_log
    #raise params.inspect
    #render json: @calories_log
    #raise params.inspect
  end
=end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  
  def home

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calories_helper.rb
module CaloriesHelper
end

app/helpers/charts_helper.rb
module ChartsHelper

  def calories_ingested_logs
    calories_ingested = current_user.calory.where("calories_type = ?", false)
    calories_burnt = current_user.calory.where("calories_type = ?", true)
    line_chart [
      {name: "Calories Ingested", data: calories_ingested.group_by_day(:created_at, last: 30).sum(:calories_number)},
      {name: "Calories Burnt", data: calories_burnt.group_by_day(:created_at, last: 30).sum(:calories_number)}
    ], xtitle: "Time - Last 30 Days", ytitle: "Consolidated Calories", download: true

  end
end

app/views/calories/create.html.erb
<h1>Calories#create</h1>
<p>Find me in app/views/calories/create.html.erb</p>

app/views/calories/destroy.html.erb
<h1>Calories#destroy</h1>
<p>Find me in app/views/calories/destroy.html.erb</p>

app/views/calories/edit.html.erb
<%=render 'shared/calories_form'%>

app/views/calories/index.html.erb
<section class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Calories Log Index
      </h1>
      <h2 class="subtitle">
        Welcome <i><%= current_user.name %></i>
      </h2>
      <%= link_to 'New Log', new_calory_path, class:"button is-link" %>
      <div class="level-right">

        <div class="level-item">
          <div class="field has-addons">

            <p class="control">
              <%= form_tag calories_path, method: :get do %>
              
                <%= label_tag :date, "Search for:" %>
                <%= date_field_tag :date, params[:date], class: "input" %>
                <%= submit_tag "Search", name: nil, class:"button is-link" %>
              <% end %>
            </p>

          </div>
        </div>
      </div>

    </div>
  </div>
</section>
<div >
  <div class= "tabs is-centered", id="paginationContainer"  >
    <%= paginate @calories %>
  </div>
</div>
<div id="tableContainer">
<table class="table" >
  <thead>
    <tr>
      <th>Log Number</th>
      <th>Calories</th>
      <th>Related Activity</th>
      <th>Type of Calories (Ingested/Burnt)</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody >
      <% @calories.each do |cal| %>
      <tr >
          <td><%= link_to cal.id, calory_path(cal) %></td>
          <td><%= cal.calories_number %></td>
          <td><%= cal.calories_related_activity %></td>
          <td><%= cal.calories_type ? "Calories Ingested":"Calories Burnt"%></td>
          <td>
            <div>
              <%= link_to 'Delete Log', calory_path(cal), method: :delete %>
              <%= link_to 'Edit Log', edit_calory_path(cal)%>
            </div>
          </td>
      </tr>
     <% end %>
  </tbody>
</table>
</div>


  <!-- Left side -->

app/views/calories/new.html.erb
<%=render 'shared/calories_form'%>

app/views/calories/show.html.erb
<div class="card">
  <header class="card-header">
    <p class="card-header-title">
      Calories Log Number: &nbsp;
       <%=@calory.id %>

    </p>

    <a href="#" class="card-header-icon" aria-label="more options">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </a>
  </header>
  <div class="card-content">
    <div class="content">
      <%= @calory.calories_related_activity %>

      <br>
      <ul>
        <li><%= @calory.calories_number %></li>
        <li><%= @calory.calories_related_activity %></li>
        <li><%= @calory.calories_type ? "Calories Ingested":"Calories Burnt"%></li>
      </ul>
      <time datetime="2016-1-1">Logged on: &nbsp;<%= @calory.created_at %></time>
    </div>
  </div>
  <footer class="card-footer">
      <a><%= link_to 'Edit Log', edit_calory_path(@calory), class:"card-footer-item"%></a>
      <a><%= link_to 'Delete Log', calory_path(@calory), method: :delete, class:"card-footer-item" %></a>
      <a><%= link_to "Back", calories_path, class:"card-footer-item" %></a>
  </footer>

</div>

app/views/charts/calories_logs.html.erb
<%= calories_ingested_logs  %>

app/views/layouts/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" >
       <%=image_tag "heartbeat-solid.svg",  width: "112", height:"28" %>
    </a>

  </div>
  <% if user_signed_in?  %>
    <% current_user.email %>
      <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
                <%= link_to 'Home', root_path, class:"navbar-item" %>
                <%= link_to 'Profile', edit_user_registration_path, class:"navbar-item" %>
          </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to 'Log out', destroy_user_session_path, class:"button is-light", method: :delete %>
          </div>
       </div>
     </div>
   </div>
   <%end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaloriesLog</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <div class="notification is-<%= message_type %>" ><%= message %></div>
    <% end %>

    <%= yield %>


  </body>
</html>

app/views/shared/_calories_form.html.erb
<div >
    <div >
      <%= link_to "Back", calories_path, class:"button is-link" %>
    </div>
</div>

<div>
  <%= form_for @calory do |u| %>
  <%= render 'shared/error_messages', object: @calory %>
    <div >
      <%= u.label "Calories Number: " %><br />
      <%= u.text_field :calories_number %><br/>
    </div>
    <div>
      <%= u.label "Type Of Calories Log: " %><br />
      <%= u.select :calories_type, options_for_select([["Calories Ingested", true], ["Calories Burnt", false]]) %>
    </div>
    <div>
      <%= u.label "Calories Log Related Activity: " %><br />
      <%= u.text_area :calories_related_activity, cols: '80', rows: '5', placeholder: "What's happening?" %><br/>
    </div>
    <%= u.submit 'SUBMIT' %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="notification is-danger">
    <div>
        The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
 </div>
<% end %>

app/views/welcome/home.html.erb
<section class="hero is-dark is-medium is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Welcome!!!
      </h1>
      <h2 class="subtitle">
        This is your Calories Log
      </h2>

      <%= link_to 'Calories Log Index', calories_path, class:"button is-link" %>

      <%= link_to 'Calories Log Chart', charts_calories_logs_path, class:"button is-link" %>

    </div>
  </div>
</section>